### ISSUE TITLE
Link funktioniert nicht

### ISSUE THREAD

**Issue by Marie981** [vovinhd/enviroomate#3]
Der Link http://https//www.haus.de/leben/trend-zero-waste-tipps-wie-sie-muell-reduzieren-und-dabei-geld-sparen in der akutellen Wochenchallenge "Lebensmittel" führt nicht zu einer Website/scheint einen Fehler zu enthalten

**Comment by tillmo** [comment]
bitte unter https://github.com/envrioomate/pwa posten
